# Generated by Django 2.1.4 on 2018-12-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('tricode', models.CharField(max_length=3)),
                ('conference', models.CharField(max_length=30)),
                ('divison', models.CharField(max_length=30)),
            ],
        ),
    ]
